---
title: "Equivalency p-Value Calculator"
resource_files:
- webcmstatrExt.js
- webcmstatrExt.wasm
- webcmstatrExt-api.js
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page provides an online calculator to a p-value for two-sample equivalency.
Based on the qualification sample statistics and the equivalency sample
statistics, this calculator computes the p-value.
The basis of this method is the following paper. More details are given
at the bottom of this page.

S. Kloppenborg, "Lot acceptance testing using sample mean and extremum with finite qualification samples," Journal of Quality Technology, 2023.
[DOI: 10.1080/00224065.2022.2147884](https://doi.org/10.1080/00224065.2022.2147884)

*This calculator is provided as-is without any warranty. Users are advised
to review the code to verify correctness.*

## Calculator
### Input
<style>
  .emscripten { padding-right: 0; margin-left: auto; margin-right: auto; display: block; }
  textarea.emscripten { font-family: monospace; width: 80%; }
  div.emscripten { text-align: center; }
  div.emscripten_border { border: 1px solid black; }
  /* the canvas *must not* have any border or padding, or mouse coords will be wrong */
  canvas.emscripten { border: 0px none; background-color: black; }

  .spinner {
    height: 50px;
    width: 50px;
    margin: 0px auto;
    -webkit-animation: rotation .8s linear infinite;
    -moz-animation: rotation .8s linear infinite;
    -o-animation: rotation .8s linear infinite;
    animation: rotation 0.8s linear infinite;
    border-left: 10px solid rgb(0,150,240);
    border-right: 10px solid rgb(0,150,240);
    border-bottom: 10px solid rgb(0,150,240);
    border-top: 10px solid rgb(100,0,200);
    border-radius: 100%;
    background-color: rgb(200,100,250);
  }
  @-webkit-keyframes rotation {
    from {-webkit-transform: rotate(0deg);}
    to {-webkit-transform: rotate(360deg);}
  }
  @-moz-keyframes rotation {
    from {-moz-transform: rotate(0deg);}
    to {-moz-transform: rotate(360deg);}
  }
  @-o-keyframes rotation {
    from {-o-transform: rotate(0deg);}
    to {-o-transform: rotate(360deg);}
  }
  @keyframes rotation {
    from {transform: rotate(0deg);}
    to {transform: rotate(360deg);}
  }

</style>
<script src="https://cdn.plot.ly/plotly-2.17.1.min.js"></script>

<label for="double-qual-mean">Qualification Sample Mean ($\bar{x}_{qual}$):</label>
<input type="number" id="double-qual-mean" min="0.001" value="100" step="0.001" required 
  onchange="this.value = Math.max(0.001, parseFloat(this.value));" /><br />
  
<label for="double-qual-sd">Qualification Sample Standard Deviation ($s_{qual}$):</label>
<input type="number" id="double-qual-sd" min="0.001" value="6" step="0.001" required 
  onchange="this.value = Math.max(0.001, parseFloat(this.value));" /><br />

<label for="int-n">Qualification Sample Size ($n$):</label>
<input type="number" id="int-n" min="3" value="18" step="1" required 
  onchange="this.value = Math.max(3, parseInt(this.value));" /><br />

<label for="double-equiv-min">Equivalency Sample Minimum ($x_{min\,equiv}$):</label>
<input type="number" id="double-equiv-min" min="0.001" value="81.4" step="0.001" required 
  onchange="this.value = Math.max(0.001, parseFloat(this.value));" /><br />
  
<label for="double-equiv-mean">Equivalency Sample Mean ($\bar{x}_{equiv}$):</label>
<input type="number" id="double-equiv-mean" min="0.001" value="94.82" step="0.001" required 
  onchange="this.value = Math.max(0.001, parseFloat(this.value));" /><br />

<label for="int-m">Equivalency Sample Size ($m$):</label>
<input type="number" id="int-m" min="3" value="8" step="1" required
  onchange="this.value = Math.max(3, parseInt(this.value));" /><br />

<figure style="overflow:visible;" id="spinner"><div class="spinner"></div><center style="margin-top:0.5em"><strong>emscripten</strong></center></figure>
<div class="emscripten" id="status">Downloading...</div>
<div class="emscripten">
  <progress value="0" max="100" id="progress" hidden=1></progress>  
</div>
<script type='text/javascript'>
  var statusElement = document.getElementById('status');
  var progressElement = document.getElementById('progress');
  var spinnerElement = document.getElementById('spinner');

  var Module = {
    preRun: [],
    postRun: [],
    print: (function() {})(),
    canvas: (function() {})(),
    setStatus: function(text) {
      if (!Module.setStatus.last) Module.setStatus.last = { time: Date.now(), text: '' };
      if (text === Module.setStatus.last.text) return;
      var m = text.match(/([^(]+)\((\d+(\.\d+)?)\/(\d+)\)/);
      var now = Date.now();
      if (m && now - Module.setStatus.last.time < 30) return; // if this is a progress update, skip it if too soon
      Module.setStatus.last.time = now;
      Module.setStatus.last.text = text;
      if (m) {
        text = m[1];
        progressElement.value = parseInt(m[2])*100;
        progressElement.max = parseInt(m[4])*100;
        progressElement.hidden = false;
        spinnerElement.hidden = false;
      } else {
        progressElement.value = null;
        progressElement.max = null;
        progressElement.hidden = true;
        if (!text) spinnerElement.hidden = true;
      }
      statusElement.innerHTML = text;
    },
    totalDependencies: 0,
    monitorRunDependencies: function(left) {
      this.totalDependencies = Math.max(this.totalDependencies, left);
      Module.setStatus(left ? 'Preparing... (' + (this.totalDependencies-left) + '/' + this.totalDependencies + ')' : 'All downloads complete.');
    }
  };
  Module.setStatus('Downloading...');
  window.onerror = function() {
    Module.setStatus('Exception thrown, see JavaScript console');
    spinnerElement.style.display = 'none';
    Module.setStatus = function(text) {
      if (text) console.error('[post-exception status] ' + text);
    };
  };
</script>
<script src=webcmstatrExt.js async></script>
<script src="webcmstatrExt-api.js"></script>

<button id="compute-p-value">Compute p-Value</button><br />

### p-Value

<textarea id="output" readonly style="width: 400px; height: 150px;"></textarea>
<br />


<script type='text/javascript'>
  document.getElementById("double-qual-mean").addEventListener("input",
    (e) => validatePositiveFloat(e.target));
  document.getElementById("double-qual-sd").addEventListener("input",
    (e) => validatePositiveFloat(e.target));
  document.getElementById("int-n").addEventListener("input",
    (e) => validateSampleSize(e.target));
  document.getElementById("double-equiv-min").addEventListener("input",
    (e) => validatePositiveFloat(e.target));
  document.getElementById("double-equiv-mean").addEventListener("input",
    (e) => validatePositiveFloat(e.target));
  document.getElementById("int-m").addEventListener("input",
    (e) => validateSampleSize(e.target));

  let power_curves = [];
  
  document.getElementById("compute-p-value").addEventListener("click", async () => {
    let k1 = 0.;
    let k2 = 0.;
    const outArea = document.getElementById("output");
    const fQualMean = validatePositiveFloat(document.getElementById("double-qual-mean"));
    const fQualSD = validatePositiveFloat(document.getElementById("double-qual-sd"));
    const iN = validateSampleSize(document.getElementById("int-n"));
    const fEquivMin = validatePositiveFloat(document.getElementById("double-equiv-min"));
    const fEquivMean = validatePositiveFloat(document.getElementById("double-equiv-mean"));
    const iM = validateSampleSize(document.getElementById("int-m"));

    outArea.value = "";
    if(fQualMean === "invalid" || fQualSD === "invalid" ||
        iN === "invalid" ||
        fEquivMin === "invalid" || fEquivMean === "invalid" ||
        iM === "invalid") {
      console.log("Invalid input");
      outArea.value = "Invalid input";
      return;
    }

    Module.setStatus("Calculating p-value... (1/2)");

    // run the rest asyncronously
    setTimeout(function () {
      const t1 = (fQualMean - fEquivMin) / fQualSD;
      const t2 = (fQualMean - fEquivMean) / fQualSD;
      const p_value = p_equiv_two_sample(Module, iN, iM, t1, t2);

      outArea.value =
`Qualification Sample: mean = ${fQualMean}, SD = ${fQualSD}, n = ${iN}\n` +
`Equivalency Sample: min = ${fEquivMin}, mean = ${fEquivMean}\n` +
`t1 = ${t1.toFixed(4)}, t2 = ${t2.toFixed(4)}\n` +
`p-value = ${p_value.toFixed(4)}`;

      Module.setStatus("");
    },
    0);
  });
</script>


## Details {.tabset}
### Method Details
Based on a user selected qualification sample statistics
($\bar{x}_{qual}$, $s_{qual}$, and $n$), equivalency
sample statistics ($x_{min\,equiv}$, $\bar{x}_{equiv}$, and $m$),
the following two statistics are computed:

$$
t_1 = \frac{\bar{x}_{qual} - x_{min\,equiv}}{s_{qual}} \\
t_2 = \frac{\bar{x}_{qual} - \bar{x}_{equiv}}{s_{qual}}
$$

From these statistics, a p-Value is computed.

### Software Details
The functionality of this page is provided by the same C++ code that is used
by the `cmstatrExt` R package. This code is compiled to WebAssembly so that
it can run inside a web browser without the user installing any special
software. This software is licensed under the
[AGPL-3](https://www.r-project.org/Licenses/AGPL-3) license.
Source code is available [here](https://github.com/cmstatr/cmstatrExt).
