// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// p_equiv
Rcpp::NumericVector p_equiv(int m, Rcpp::NumericVector t1, Rcpp::NumericVector t2);
RcppExport SEXP _cmstatrExt_p_equiv(SEXP mSEXP, SEXP t1SEXP, SEXP t2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t2(t2SEXP);
    rcpp_result_gen = Rcpp::wrap(p_equiv(m, t1, t2));
    return rcpp_result_gen;
END_RCPP
}
// k_equiv_two_sample
Rcpp::NumericVector k_equiv_two_sample(double alpha, int n, int m);
RcppExport SEXP _cmstatrExt_k_equiv_two_sample(SEXP alphaSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(k_equiv_two_sample(alpha, n, m));
    return rcpp_result_gen;
END_RCPP
}
// p_equiv_two_sample
Rcpp::NumericVector p_equiv_two_sample(int n, int m, Rcpp::NumericVector t1, Rcpp::NumericVector t2);
RcppExport SEXP _cmstatrExt_p_equiv_two_sample(SEXP nSEXP, SEXP mSEXP, SEXP t1SEXP, SEXP t2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t2(t2SEXP);
    rcpp_result_gen = Rcpp::wrap(p_equiv_two_sample(n, m, t1, t2));
    return rcpp_result_gen;
END_RCPP
}
// run_tests
int run_tests();
RcppExport SEXP _cmstatrExt_run_tests() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(run_tests());
    return rcpp_result_gen;
END_RCPP
}
// power_sim
DataFrame power_sim(const int n_qual, const int m_equiv, const int rep_qual, const int rep_equiv, const double mu_qual, const double sigma_qual, NumericVector mu_equiv, NumericVector sigma_equiv, const double k1, const double k2);
RcppExport SEXP _cmstatrExt_power_sim(SEXP n_qualSEXP, SEXP m_equivSEXP, SEXP rep_qualSEXP, SEXP rep_equivSEXP, SEXP mu_qualSEXP, SEXP sigma_qualSEXP, SEXP mu_equivSEXP, SEXP sigma_equivSEXP, SEXP k1SEXP, SEXP k2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n_qual(n_qualSEXP);
    Rcpp::traits::input_parameter< const int >::type m_equiv(m_equivSEXP);
    Rcpp::traits::input_parameter< const int >::type rep_qual(rep_qualSEXP);
    Rcpp::traits::input_parameter< const int >::type rep_equiv(rep_equivSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_qual(mu_qualSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma_qual(sigma_qualSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_equiv(mu_equivSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma_equiv(sigma_equivSEXP);
    Rcpp::traits::input_parameter< const double >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< const double >::type k2(k2SEXP);
    rcpp_result_gen = Rcpp::wrap(power_sim(n_qual, m_equiv, rep_qual, rep_equiv, mu_qual, sigma_qual, mu_equiv, sigma_equiv, k1, k2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cmstatrExt_p_equiv", (DL_FUNC) &_cmstatrExt_p_equiv, 3},
    {"_cmstatrExt_k_equiv_two_sample", (DL_FUNC) &_cmstatrExt_k_equiv_two_sample, 3},
    {"_cmstatrExt_p_equiv_two_sample", (DL_FUNC) &_cmstatrExt_p_equiv_two_sample, 4},
    {"_cmstatrExt_run_tests", (DL_FUNC) &_cmstatrExt_run_tests, 0},
    {"_cmstatrExt_power_sim", (DL_FUNC) &_cmstatrExt_power_sim, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_cmstatrExt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
