# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runTests <- function() {
    .Call(`_cmstatrExt_runTests`)
}

#' @export
rcpp_hello_world <- function() {
    .Call(`_cmstatrExt_rcpp_hello_world`)
}

