# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' p-Value for one-sample equivalency
#'
#' @description
#' Calculates the p-Value for a one-sample acceptance test
#' based on Vangel (2002).
#' This test considers the sample size of the acceptance sample (`m`).
#'
#' Two test statistics are required:
#'
#' t1 = (mu - Y_min) / sigma
#'
#' t2 = (mu - Y_mean) / sigma
#'
#' Where:
#' - mu is the mean of the population
#' - sigma is the standard deviation of the population
#' - Y_min is the minimum from the acceptance sample
#' - Y_mean is the mean of the acceptance sample
#'
#' @param m the size of the acceptance sample
#' @param t1 the test statistic described above. May be a vector.
#' @param t2 the test statistic described above. May be a vector.
#'
#' @return a vector of p-Values of the same length as t1 and t2
#'
#' @export
p_equiv <- function(m, t1, t2) {
    .Call(`_cmstatrExt_p_equiv`, m, t1, t2)
}

#' Calculate the factors for a two-sample acceptance test
#'
#' @description
#' Calculates the factors k1 and k2, which are used for setting acceptance
#' values for lot acceptance. These factors consider both the
#' size of the qualification sample (`n`)
#' and the size of acceptance sample (`m`).
#' This test is detailed in a forthcoming paper.
#'
#' @param alpha the desired probability of Type 1 error
#' @param n the size of the qualification sample
#' @param m the size of the acceptance sample
#'
#' @return
#' A vector of length 2 with the contents `c(k1, k2)`
#'
#' @export
k_equiv_two_sample <- function(alpha, n, m) {
    .Call(`_cmstatrExt_k_equiv_two_sample`, alpha, n, m)
}

#' p-Value for two-sample equivalency
#'
#' @description
#' Calculates the p-Value for a two-sample acceptance test.
#' This test considers the sample size of the qualification
#' sample (`n`) and the acceptance sample (`m`).
#'
#' Two test statistics are required:
#'
#' t1 = (X_mean - Y_min) / S
#'
#' t2 = (X_mean - Y_mean) / S
#'
#' Where:
#' - X_mean is the mean of the qualification sample
#' - S is the standard deviation of the qualification sample
#' - Y_min is the minimum from the acceptance sample
#' - Y_mean is the mean of the acceptance sample
#'
#' @param n the size of the qualification sample
#' @param m the size of the acceptance sample
#' @param t1 the test statistic described above. May be a vector.
#' @param t2 the test statistic described above. May be a vector.
#'
#' @return a vector of p-Values of the same length as t1 and t2
#'
#' @export
p_equiv_two_sample <- function(n, m, t1, t2) {
    .Call(`_cmstatrExt_p_equiv_two_sample`, n, m, t1, t2)
}

run_tests <- function() {
    .Call(`_cmstatrExt_run_tests`)
}

#' @export
power_sim <- function(n_qual, m_equiv, rep_qual, rep_equiv, mu_qual, sigma_qual, mu_equiv, sigma_equiv, k1, k2) {
    .Call(`_cmstatrExt_power_sim`, n_qual, m_equiv, rep_qual, rep_equiv, mu_qual, sigma_qual, mu_equiv, sigma_equiv, k1, k2)
}

