# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the factors for a two-sample acceptance test
#'
#' @export
k_equiv_two_sample <- function(n, m, alpha) {
    .Call(`_cmstatrExt_k_equiv_two_sample`, n, m, alpha)
}

runTests <- function() {
    .Call(`_cmstatrExt_runTests`)
}

